language: android

matrix:
  include:
    - os: linux
      jdk: oraclejdk8
      addons:
        apt:
          packages:
            - graphviz
      sudo: false
    - os: osx
      osx_image: xcode9.2 # Will give us JDK 1.8.0_112-b16
      dist: precise # https://github.com/travis-ci/travis-ci/issues/5990#issuecomment-216621501
      sudo: required

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install graphviz; fi
  # Install SDK license so Android Gradle plugin can install deps.
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-license"

script: ./gradlew clean build

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - .buildscript/deploy_snapshot.sh

env:
  global:
    - secure: "fo9HUps/nNCI2bW9yzGCB79lhh0EWBPXz9WBro50AT2Fm1E/ofVP2cZG1ZP8hFmt1oJxaRwHuzn6Pq2zNd/b0wuM7xbhnBiWaBkoguYS62N536xSJVi0xvM6VM/oSDqClS1WNH8f44fXB8JB68NwP31mUSc0DC5nJd9MUA2LZEQ8Abj9l04Cu/Iq1CjRi9u0wxkbK2A8/cqjfzfSS63G0E1Z9K+PG8rH+yB4eQK3mfNh+gDiI3Jyc93xM7oahRlGv1nCVdVYvRQG/AvRZQ4EF8UuMP73o4XisBBS2AfGdDUXSi+v3XS18Vz41ynNm4tyF/443M1sSRAz1LGWArGKehR6WG8PJB26K0Ag7WZLkSRzu58Uz6dNNcjztrUK+PUuvEuLK1WKjeeqLCEDCVgWT9ujQE/RFMzXaT6rPLP1hnLnWitUU6DUJb5A/JB0lo9lBt6PjTM8RXY7K3x7xV3lVnJDKVTv1EXe5hk2wZxyCtIqR0F3h6E3QIDMC0SFFYPvz7eiiwStIDv7QIZw594jt/xbM94fxGziSP+Ti1mP2GKAPfEtNea6+XVMN4jJgSPpT8vL5vW54WhHAWUkDPL+q/V+lMGuloRN+AS/LOWTX8lF0YF9vO5HmhV8UY6eBEXUhOuSRZBW1RqMEz+yDpS8Tu7eA5lFDmnnheOtledsiQA="
    - secure: "pNKrYMTjU0/Qyn1AG8YnPkxR3q8l61Z34pISGUr9c7sQK9hMiZ45dGYkqNmAoaK/lsiU6hvIOo7DCsxij4RnyLZZmUrrMtr2P9Vw1RxJjoPFtygQ0QVMT+9BE1Zynb//HyaJhVd+S4AYUBtuLs6tn78FkDmRCF9ZVu7B91kOdawIx9bgeJ2kHMileCe3Gpbcp/4/C/umD6xIcV3v6UUJCRKnEMGFj9BerLZHQRwiE18Bjz86nHnrQZEaM0gV1ZSKfA3gINCR6BWboikkk8FpmieiGJIcsS6p8mdzrQ5QeBFzdwFnFi07vbG7U8SBtPFDAnOiyPw/qmInWaK+I2v92KI4jpDfKF1lRr/bxdxLVAowuj45uxoj6z0AiUm95YgnPP34/4yw7aaTz+sGd+5XTqQSvzDtU8mIko8iUcDTdsCZS589qZQFf6HbVPVGSO+3pKgbALg6QY6YJgI5D1uC6O2H/iOPhUaD/+Eujm4ETdlmXhvlZVF4wM+6qvK7m3ms7vEvhcC9Dg4UlIYFIiEYH/faxP2EogL9V6qR+4AjCfPkefq2DOHFrc6FmvJ8hYa7PAyfEKXdErJZob0HB9is5o6Y+IcrC73FswVYxnKAm2BJOfF/i4pGX/PhfkIpzuG4QtefGyCJYBYpG68mdkPPg/wveQeun+R6EKXiWnIqqSM="

branches:
  except:
    - gh-pages

notifications:
  email: false

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache